apiVersion: apps/v1
kind: Deployment
metadata:
  name: contract
  namespace: sharetrip
spec:
  replicas: 2
  selector:
    matchLabels:
      app: contract
  template:
    metadata:
      labels:
        app: contract
    spec:
      containers:
        - name: contract
          image: sharetrip/contract:local
          ports:
            - containerPort: 8082
          envFrom:
            - configMapRef:
                name: contract-config
            - secretRef:
                name: contract-secret
